name: "cargo-deny"
description: "Help manage Cargo crate dependencies and validate licenses"
author: "Embark Studios"

branding:
  icon: "slash"
  color: "red"

inputs:
  command:
    description: "The command to run with cargo-deny"
    required: false
    default: "check"
  arguments:
    description: "The arguments to pass to cargo-deny"
    required: false
    default: "--all-features"
  log-level:
    description: "The log level for cargo-deny"
    required: false
    default: "warn"

runs:
  using: "docker"
  image: "ghcr.io/embarkstudios/cargo-deny-action:latest"
  args:
    - --log-level
    - ${{ inputs.log-level }}
    - ${{ inputs.arguments }}
    - ${{ inputs.command }}
